### ISSUE TITLE
Implement ReplyTo

### ISSUE THREAD

**Issue by StephenRedd** [NullDesk/NullMailer#42]
Implement ReplyTo through message model in addition to the sender address and display name

**Comment by senj** [comment]
Hey, what about the Cc and Bcc Recipients?

**Comment by StephenRedd** [comment]
This hasn't been a priority so far. 

This is an opinionated framework in many ways, and is generally intended for automated and application originated messaging. Basically, systems that generate emails in response to system events, or similar things. As currently designed, the extensions automatically split messages with multiple recipients before delivery, and each recipient instead receives their own isolated email.  

If we got into CC and BCC behaviors, we'd also have to address multiple TO recipients within a single email message as well. I'm not necessarily opposed to that, but in reality it would be nearly impossible for me to support the full range of possible email scenarios in a service agnostic abstraction layer; which is ultimately what this is. So no matter what features this ends up supporting, it will always be a sub-set of what the native mail service frameworks provide.

If you have usages that need this type of behavior though, please let me know the specific scenarios you have in mind, and tell me a little about why you'd use these extensions instead of the native SMTP or SendGrid libraries directly. I can use that information to see what I can do to incorporate new features and prioritize then in the design.

I also should update the docs a bit to highlight the intent a little better.

**Comment by senj** [comment]
Now that I know how it works it makes sense.
