### ISSUE TITLE
Question - mailer's use of the unit-of-work pattern

### ISSUE THREAD

**Issue by StephenRedd** [NullDesk/NullMailer#57]
Out of the box, the 3.x mailer implementation follows a unit-of-work pattern, very similar in design to how entity framework's DbContext works. The intended usage is as follows:

* Create a mailer instance
* Add one or more tracked messages to the mailer
* Send the messages
* Dispose the mailer when done

This is handy in that it keeps the delivery history available in the mailer instance after sending the messages.

After having implemented this in several client applications though, it seems that this intent may not be clear to developers using the library. This can be a problem if developers re-use the mailer instance over and over without disposing it. The messages already sent remain in memory, and if there are attachments this could hold open file stream or include a lot of in-memory attachment data. 

I could do one of three things with version 4:

* Clear all tracked delivery items that have already been sent from the mailer instance when send or send all is called (it would track delivered items only for the most recent send call).
  * This could be counter-intuitive in some cases 
* Clear all messages tracked by the entity after messages are sent (it would track no delivered items at all)
  * This effectively turns the "tracked messages" array into a "pending messages" array instead; and would need some renaming to make that clear to the developer.
* Change the behavior entirely so that adding a message immediately sends the message, and the mailer doesn't track multiple messages in-memory at all. 
  * This moves away from unit-of-work entirely.
  * Callers would need to rely on a history store if they wished to retrieve status about messages outside the scope of the calling code.

Any opinions, suggestions or ideas?

**Comment by naymore** [comment]
Not exactly a suggestion but maybe you can make any sense of it ;-)

First of all I think you make yourself pretty clear here:
> [...] it is best to register the mailers to be transient instances [...]

As you stated in another issue post this abstraction (NullMailer) is meant to be used for automated processes typically triggered by some kind of event.

This meets exactly my intentions. And living in a microservices world, this makes it a perfect candidate for just that. Single responsibility. Send e-mails. Of course I want this service to be as lightweight (memory-wise and protocol-chattiness-wise) as possible.

I don't think I need message tracking. Can you please elaborate what that actually is? :-)
Isn't a unit of work what you describe in your last bullet point when you say "get message and send it" - job done? Don't you have a SQL message store for when you need to go back in time? 
Also as much as I like the feature I am not sure if it is NullMailers primary concern (which is sending of e-mails). 

Anyway... to cut a long story short: I like the library and the work you have put into it! The most critical aspect for me is a rock solid and lightweight solution.  If anything adds to that goal I'm in! ;-)

**Comment by StephenRedd** [comment]
That's good information, I appreciate it!

Tracking in this case is simple; it just means when you add a message to a mailer, it keeps track of each resulting delivery item in an array. You can tell which were delivered and which were pending. It isn't as ambitious as tracking in EF of course, but it does keep up with them until you dispose your mailer instance.

For microservices of course, you probably don't care about keeping a reference to delivery items after they have been sent out. 

I'm leaning towards having the default behavior just remove items once the send/send all is called; but having the option to turn on full tracking if you want to keep sent items (like it does now).

**Comment by senj** [comment]
Hi, we had an error yesterday where we tried to send a mail with invalid address
```
Exception:MailKit.Net.Smtp.SmtpCommandException: 5.1.3 Invalid address
```

The problem was, that after the error our mail service was unable to send any other mails:
```
Logger:NullDesk.Extensions.Mailer.MailKit.MkSmtpMailer :: Exception:System.InvalidOperationException: The SmtpClient is already connected.
```

Is there a way to resolve this in client code or is it a bug? One error shouldn't break the system.. :/
Or do we have to use a try/catch here?
This is our implementation:

In Startup, we have: 
```
services.AddTransient<IMailer, MkSmtpMailer>();
```
```
if (mailMessage.IsDeliverable)
            {
                IEnumerable<Guid> messages = _mailer.AddMessage(mailMessage);

                    DeliveryItem delivery = await _mailer.SendAsync(messages.First());
                    trace.AddAnnotation(Annotations.Tag("result", delivery.IsSuccess.ToString()));

                    if (!delivery.IsSuccess)
                    {
                        return new EnqueueResult(false, delivery.ExceptionMessage);
                    }

                    return new EnqueueResult(true);
                }

            return new EnqueueResult(false, "Mail is not deliverable");
```

**Comment by StephenRedd** [comment]
Based on early feedback, and my own experiences with projects using the extensions I've decided that 3.3.0 should go ahead and change the default behavior to throw away the internally tracked delivery items when SendAll is complete. A property will be provided that allows the caller to override this behavior and keep tracked items. 

This has the minimal impact on current usages, while doing the most to protect against unwanted memory leakage and holding file streams open unnecessarily.

**Comment by StephenRedd** [comment]
Actually, after looking at the code again it shouldn't be a large impact to just change the array to "pending items" to clarify intent, and just always remove them after sending the messages.
