### ISSUE TITLE
Cascading error after trying to send invalid mail

### ISSUE THREAD

**Issue by senj** [NullDesk/NullMailer#58]
Hi, we had an error yesterday where we tried to send a mail with invalid address
```
Exception:MailKit.Net.Smtp.SmtpCommandException: 5.1.3 Invalid address
```

The problem was, that after the error our mail service was unable to send any other mails:
```
Logger:NullDesk.Extensions.Mailer.MailKit.MkSmtpMailer :: Exception:System.InvalidOperationException: The SmtpClient is already connected.
```

Is there a way to resolve this in client code or is it a bug? One error shouldn't break the system.. :/
Or do we have to use a try/catch here? My expectation would be that .NET disposes the injected client even on an exception.
This is our implementation:

In Startup, we have: 
```
services.AddTransient<IMailer, MkSmtpMailer>();
```
and when sending the mail:
```
private readonly IMailer _mailer;

        public SmtpClientPool(IMailer mailer)
        {
            _mailer = mailer;
        }

        public async Task<EnqueueResult> SendMailAsync(MailerMessage mailMessage)
        {
            if (mailMessage.IsDeliverable)
            {
                IEnumerable<Guid> messages = _mailer.AddMessage(mailMessage);

                using (ClientTrace trace = new ClientTrace("Email", "Send mail to SMTP"))
                {
                    DeliveryItem delivery = await _mailer.SendAsync(messages.First());
                    trace.AddAnnotation(Annotations.Tag("result", delivery.IsSuccess.ToString()));

                    if (!delivery.IsSuccess)
                    {
                        return new EnqueueResult(false, delivery.ExceptionMessage);
                    }

                    return new EnqueueResult(true);
                }
            }

            return new EnqueueResult(false, "Mail is not deliverable");
        }
```

**Comment by StephenRedd** [comment]
I would imagine that your private _mailer may not be disposed, so all mail could be using the same mailer instance over and over. Of course, that depends on if the SmtpClientPool instance is itself being reused or not. It might not be in your case, it would depend on if you have a DI framework instantiating this class, and what kind of lifecycle it uses. 

To make sure you aren't re-using the mailer, you could do something like this instead: 

```
        private readonly Func<IMailer> _getMailerFunc;

        public SmtpClientPool(Func<IMailer> getMailerFunc)
        {
            _getMailerFunc= getMailerFunc;
        }

        public async Task<EnqueueResult> SendMailAsync(MailerMessage mailMessage)
        {
            if (mailMessage.IsDeliverable)
            {
                //stuff
                using (ClientTrace trace = new ClientTrace("Email", "Send mail to SMTP"))
                {
                    using(var mailer = getMailerFunc())
                    {
                        DeliveryItem delivery = await _mailer.SendAsync(messages.First());
                        // stuff
                    }
                }
            }
            //return stuff
        }
```
You could also make use of the built-in factory and get instances of the mailer from the factory (if there isn't a DI framework in play creating SmtpClientPool instances for you).

```
        private readonly MailerFactory _mailerFactory;

        public SmtpClientPool(Func<IMailer> mailerFactory)
        {
            _mailerFactory= mailerFactory;
        }
         public async Task<EnqueueResult> SendMailAsync(MailerMessage mailMessage)
        {
            // stuff
            using(var mailer = _mailerFactory.GetMailer()
            {
                //stuff
            }
        }
```

**Comment by StephenRedd** [comment]
Anyway, I completely agree that no matter what, the mailer shouldn't blow up on an exception, even if you are making re-use of it.

I ran into some similar problems with the way MailKit's client is implemented when I was doing some parallel usage testing. 

MailKit's client is designed for high-volume scenarios, so it can connect and hold an active connection with the SMTP server for a very long time. I understand and agree with the MailKit client deisgn, but the separation of connecting, sending, and closing the client connection is a real pain in the backside sometimes.

It's an easy case to manage though, so I'll make sure I get more tests for your scenario in place and shore up the reliability for version 3.3.0.

**Comment by senj** [comment]
Sorry for commenting on a closed issue, but would the MailerFactory be a singleton or transient?

**Comment by StephenRedd** [comment]
If you wanted to use DI with the factory, you could register it with a singleton lifecycle. Typically though, you'd just register IMailer (and IHistory) directly, but there is nothing stopping you from using the factory instead. 

If you aren't using DI though, you can just instantiate the factory and assign it to some globally available static property somewhere, or wrap it in a class using the singleton design pattern if you want.
